### ISSUE TITLE
Specification of End User Consumption

### ISSUE THREAD

**Issue by jumarmartin** [elonsoc/ods#4]
Users need the ability to access the resources that are provided to them through a simple to use frontend but that presentation layer must be informed by some system in the context of the user performing an action. Different types of users have different types of resources provided to them and this information is provided by the backend to help the user leverage the APIs provided to them as quick as possible.

Assuming proper controls in the backend, how should we inform the frontend and thus the user? How can a user commit to actions on _their_ APIs? Should we tie an API key to a user or instead have them register an application? How should we display this information to a user?

Prior Art:
- [Harvard API Fundamentals](https://portal.apis.huit.harvard.edu/api-fundamentals)
- [Registering an Application and getting an API Key from Harvard](https://portal.apis.huit.harvard.edu/register-an-app#top)
- [Yale API](developers.yale.edu)

**Comment by SheedGuy** [comment]
oops!
