### ISSUE TITLE
[backend] Bearer <token> 401's on Correct Token

### ISSUE THREAD

**Issue by jumarmartin** [elonsoc/ods#50]
Following the [usage guide on authentication](https://ods.elon.edu/docs/usage-guides/authentication) to make a call to the api requires the header `Authorization: Bearer <API_KEY>`. When supplying it, I get a 401.

It seems like if we don't supply "Bearer" (which we should) then it works!

## Reproduction

Run the following with a proper api key:
`curl -X GET https://api.ods.elon.edu/ping -H "Authorization: Bearer <VALID_API_KEY>"`

We should get an empty body with a 200. Instead, we get a 401.

When running the same `curl` command without "Bearer" in the header, we get the 200:

`curl -X GET https://api.ods.elon.edu/ping -H "Authorization: <VALID_API_KEY>"`

When ran in Insomnia:
<img width="985" alt="image" src="https://github.com/elonsoc/ods/assets/20880969/5efdca80-b0d3-440e-9390-6c9981ef0968">
<img width="986" alt="image" src="https://github.com/elonsoc/ods/assets/20880969/ef30a162-16ac-44e0-a144-e2c0a22e53e1">

**Comment by ejrcarr** [comment]
Done
